### PR TITLE
GraphQL improvements for v4

### LINKED ISSUE #2377: Support array properties in parquet serialisation
- [x] Add support for `PropType::Array` when writing to parquet
- [x] Re-enable all tests marked with `TODO: #2377`

### LINKED ISSUE #2384: fix the writing of graphs in graphql
Currently writing a graph to disk from graphql causes the vector database/indexes to be lost because the folder gets overwritten. This also fails on windows because the vector database is open

### PR DESCRIPTION
**Pull request by ljeub-pometry**
### What changes were proposed in this pull request?

- support for atomic replacements of graphs/folders/namespaces
- rework of the internal folder structures

### Why are the changes needed?

fixes #2377 (reenables the tests and fixes serialisation)
fixes #2384

### CODE REVIEW

File: db4-graph/src/lib.rs [hunk 1]
```diff
@@ -212,8 +212,9 @@ impl<EXT: PersistentStrategy<NS = NS<EXT>, ES = ES<EXT>, GS = GS<EXT>>> Temporal
         })
     }
 
-    pub fn disk_storage_enabled(&self) -> bool {
-        self.graph_dir().is_some() && Extension::disk_storage_enabled()
+    pub fn disk_storage_enabled(&self) -> Option<&Path> {
```
Comment (fabubaker) [inline db4-graph/src/lib.rs]: Since this no longer returns a boolean maybe rename to `disk_storage_path`?

Comment (fabubaker) [reply db4-graph/src/lib.rs]: Also need to update the doc comment in the `InternalStorageOps` trait.

File: raphtory-graphql/src/model/graph/mutable_graph.rs [hunk 2]
```diff
@@ -439,31 +411,18 @@ impl GqlMutableGraph {
     /// Post mutation operations.
     async fn post_mutation_ops(&self) {
         self.graph.set_dirty(true);
-
```
Comment (fabubaker) [inline raphtory-graphql/src/model/graph/mutable_graph.rs:442]: If we're not planning on adding more functionality to `post_mutation_ops`, we should get rid of it and just directly call `set_dirty` - would much rather make it explicit than hide it behind a vaguely named method.

File: raphtory-graphql/src/model/graph/namespace.rs [hunk 3]
```diff
@@ -3,73 +3,141 @@ use crate::{
...
+                relative_path: relative_path.into(),
+            })
+        } else {
+            Err(PathValidationError::NamespaceDoesNotExist(
+                relative_path.into(),
+            ))
+        }
+    }
+
+    pub fn new_child_namespace(&self, relative_path: &str) -> Result<Self, PathValidationError> {
```
Comment (fabubaker) [inline raphtory-graphql/src/model/graph/namespace.rs]: This method seems to be unused?

File: raphtory-graphql/src/model/graph/namespace.rs [hunk 4]
```diff
@@ -3,73 +3,141 @@ use crate::{
...
+        let relative_path = [&self.relative_path, relative_path].join("/");
+        Self::try_from_valid(current_dir, relative_path)
+    }
+
+    pub fn try_new_child(&self, file_name: &str) -> Result<NamespacedItem, PathValidationError> {
+        let current_dir = valid_path(self.current_dir.clone(), file_name)?;
+        let relative_path = if self.relative_path.is_empty() {
+            file_name.to_owned()
+        } else {
+            [&self.relative_path, file_name].join("/")
```
Comment (fabubaker) [inline raphtory-graphql/src/model/graph/namespace.rs:99]: Does this work on Windows? Shouldn't we use `PathBuf.join` or similar?

File: raphtory-graphql/src/model/graph/namespace.rs [hunk 5]
```diff
@@ -92,16 +160,23 @@ impl Namespace {
...
-        if parent.starts_with(&self.base_dir) {
-            Some(Namespace::new(self.base_dir.clone(), parent))
-        } else {
+        if self.relative_path.is_empty() {
             None
+        } else {
+            let parent = self.current_dir.parent()?.to_path_buf();
+            let relative_path = self
+                .relative_path
+                .rsplit_once("/")
```
Comment (fabubaker) [inline raphtory-graphql/src/model/graph/namespace.rs:168]: Does this work on windows?

File: raphtory-graphql/src/paths.rs [hunk 6]
```diff
@@ -1,198 +1,683 @@
...
-                    )))
-            }
-            Component::Prefix(_)
-            | Component::RootDir
-            | Component::CurDir
-            | Component::ParentDir => Err(GraphError::from(InvalidPathReason::PathNotParsable(
-                self.to_error_path(),
-            ))),
-        }
+    fn replace_graph_data_inner(
```
Comment (fabubaker) [inline raphtory-graphql/src/paths.rs]: Considering this method is only used in `replace_graph_data`, do you want to just inline its contents there?

File: raphtory-graphql/src/paths.rs [hunk 7]
```diff
@@ -1,198 +1,683 @@
...
+
+    Ok(full_path)
 }
 
 pub(crate) fn valid_path(
     base_path: PathBuf,
     relative_path: &str,
-    namespace: bool,
-) -> Result<PathBuf, InvalidPathReason> {
+) -> Result<ValidPath, PathValidationError> {
```
Comment (fabubaker) [inline raphtory-graphql/src/paths.rs]: This method seems like it belongs to `ValidPath` as a constructor.

File: raphtory-graphql/src/paths.rs [hunk 8]
```diff
@@ -1,198 +1,683 @@
...
+    if full_path.is_symlink() {
+        return Err(InvalidPathReason::SymlinkNotAllowed.into());
+    }
+    ensure_clean_folder(&full_path)?;
+    Ok(())
 }
 
-impl Deref for ValidGraphFolder {
-    type Target = GraphFolder;
+fn valid_path_inner(
```
Comment (fabubaker) [inline raphtory-graphql/src/paths.rs]: Might as well inline this into `valid_path` since it's not used anywhere else.

File: raphtory-graphql/src/paths.rs [hunk 9]
```diff
@@ -1,198 +1,683 @@
...
+                InternalPathValidationError::InvalidPath(reason) => {
+                    PathValidationError::InvalidPath { graph, reason }
+                }
+                _ => PathValidationError::InternalError { graph, error },
+            }
         })
     }
+}
+
+fn is_graph(path: &Path) -> bool {
```
Comment (fabubaker) [inline raphtory-graphql/src/paths.rs]: This method is unused.

File: raphtory-graphql/src/paths.rs [hunk 10]
```diff
@@ -1,198 +1,683 @@
...
 
-#[derive(Clone, Debug, PartialOrd, PartialEq, Ord, Eq)]
-pub struct ExistingGraphFolder {
-    folder: ValidGraphFolder,
+pub trait ValidGraphPaths {
+    fn local_path(&self) -> &str;
+
+    fn graph_folder(&self) -> &impl GraphPaths;
+
+    fn local_path_string(&self) -> String {
```
Comment (fabubaker) [inline raphtory-graphql/src/paths.rs]: This method is just a thin wrapper, IMO we should punt it and just directly call `to_owned`.

File: raphtory/src/serialise/graph_folder.rs [hunk 11]
```diff
@@ -1,47 +1,298 @@
...
 /// Folder structure:
 ///
 /// GraphFolder
-/// ├── graph/        # Graph data
-/// ├── .raph         # Metadata file
-/// ├── index/        # Search indexes (optional)
-/// └── vectors/      # Vector embeddings (optional)
+/// ├── .raph         # Metadata file (json: {path: "data_{id}"})
+/// └── data_{id}/    # Data folder (incremental id for atomic replacement)
+///     ├── .raph         # Metadata file (json: {path: "graph_{id}", meta: {}})
```
Comment (fabubaker) [inline raphtory/src/serialise/graph_folder.rs]: This should be `.meta` right? As per https://github.com/Pometry/Raphtory/issues/2384#issuecomment-3570752631

File: raphtory/src/serialise/graph_folder.rs [hunk 12]
```diff
@@ -1,47 +1,298 @@
...
 /// A container for managing graph data.
+///
 /// Folder structure:
 ///
 /// GraphFolder
-/// ├── graph/        # Graph data
-/// ├── .raph         # Metadata file
-/// ├── index/        # Search indexes (optional)
-/// └── vectors/      # Vector embeddings (optional)
+/// ├── .raph         # Metadata file (json: {path: "data_{id}"})
```
Comment (fabubaker) [inline raphtory/src/serialise/graph_folder.rs]: This important doc comment really belongs at the top of this file, right above all the `*_PATH` variables.

File: raphtory/src/serialise/graph_folder.rs [hunk 13]
```diff
@@ -1,47 +1,298 @@
...
 
 /// Stores graph data
 pub const GRAPH_PATH: &str = "graph";
+pub const DEFAULT_GRAPH_PATH: &str = "graph0";
+
+pub const DATA_PATH: &str = "data";
+pub const DEFAULT_DATA_PATH: &str = "data0";
 
 /// Stores graph metadata
 pub const META_PATH: &str = ".raph";
```
Comment (fabubaker) [inline raphtory/src/serialise/graph_folder.rs]: Shouldn't there be a `.meta` file, as per https://github.com/Pometry/Raphtory/issues/2384#issuecomment-3570752631?

File: raphtory-graphql/src/model/graph/namespace.rs (hunk 4 above)
Comment (fabubaker) [reply raphtory-graphql/src/model/graph/namespace.rs:99]: As discussed in standup, this is fine as these are namespaces and not filesystem paths.

File: raphtory-graphql/src/model/graph/namespace.rs (hunk 5 above)
Comment (fabubaker) [reply raphtory-graphql/src/model/graph/namespace.rs:168]: As discussed in standup, this is fine as these are namespaces and not filesystem paths.

**Review by fabubaker — COMMENTED** [review]
Some minor readability comments. Only went through about half of the PR, will leave the rest to @miratepuffin.

File: raphtory-graphql/src/paths.rs (hunk 8 above)
Comment (ljeub-pometry) [reply raphtory-graphql/src/paths.rs]: These are split up like this to simplify the error handling (this on returns an internal error and the other function then adds the graph path for nicer error messages)

File: raphtory-graphql/src/model/graph/mutable_graph.rs (hunk 2 above)
Comment (ljeub-pometry) [reply raphtory-graphql/src/model/graph/mutable_graph.rs:442]: I left it for now as there is a decent chance we want to add more things here later, can always revisit
